services:
  menu-app:
    build:
      context: .
      dockerfile: Containerfile
    container_name: menu-website
    ports:
      - '5874:80'
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - menu-network

networks:
  menu-network:
    driver: bridge
